#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '0':
        pose: rigid_body_0/pose
        child_frame_id: rigid_body_0
#        frame_id: odom
        address: 3724
        x_init: 0.1
        y_init: 0.1
    '1':
        pose: rigid_body_1/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_1
#        frame_id: odom
        address: 3724
        x_init: 0.1
        y_init: 0.1
    '2':
        pose: rigid_body_2/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_2
#        frame_id: odom
        address: 3222
        x_init: 0.1
        y_init: 0.1  
    '3':
        pose: rigid_body_3/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_3
#        frame_id: odom
        address: 3714
        x_init: 0.1
        y_init: 0.1  
    '4':
        pose: rigid_body_4/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_4
#        frame_id: odom
        address: 3790
        x_init: 0.1
        y_init: 0.1  
    '5':
        pose: rigid_body_5/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_5
#        frame_id: odom
        address: 3807
        x_init: 0.1
        y_init: 0.1          
    '6':
        pose: rigid_body_6/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_6
#        frame_id: odom
        address: 3658
        x_init: 0.1
        y_init: 0.1   
    '7':
        pose: rigid_body_7/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_7
#        frame_id: odom
        address: 3761
        x_init: 0.1
        y_init: 0.1    
    '8':
        pose: rigid_body_8/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_8
#        frame_id: odom
        address: 3778
        x_init: 0.1
        y_init: 0.1  
    '9':
        pose: rigid_body_9/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_9
#        frame_id: odom
        address: 3789
        x_init: 0.1
        y_init: 0.1    
    '10':
        pose: rigid_body_10/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_10
#        frame_id: odom
        address: 3748
        x_init: 0.1
        y_init: 0.1    
    '11':
        pose: rigid_body_11/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_11
#        frame_id: odom
        address: 3733
        x_init: 0.1
        y_init: 0.1    
    '12':
        pose: rigid_body_12/pose
#    pose2d: rigid_body_1/ground_pose
        child_frame_id: rigid_body_12
#        frame_id: odom
        address: 3755
        x_init: 0.1
        y_init: 0.1                                                                                                                               
   #Use this format to create each new rigid body

   #'2':
   #    pose: rigid_body_2/pose
   #    pose2d: rigid_body_2/ground_pose
   #    frame_id: rigid_body_2/base_link

optitrack_config:
#	multicast_address: 192.169.209.203
       multicast_address: 224.0.0.1
