
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '30':
        pose: Robot_1/pose
        pose2d: Robot_1/ground_pose
        child_frame_id: base_link
        parent_frame_id: map_mocap
    '20':
        pose: mocap_obstacle1/pose
        pose2d: mocap_obstacle1/ground_pose
        child_frame_id: obst1/base_link
        parent_frame_id: map_mocap
    '21':
        pose: mocap_obstacle2/pose
        pose2d: mocap_obstacle2/ground_pose
        child_frame_id: obst2/base_link
        parent_frame_id: map_mocap
#optitrack_config:
#        multicast_address: 192.0.0.1
#        multicast_address: 224.0.0.1
#        multicast_address: 234.255.42.99
