# #
# # Definition of all trackable objects
# # Identifier corresponds to Trackable ID set in Tracking Tools
# #
# rigid_bodies:
#     '0':
#         address: 3808                                                                                                            
#    #Use this format to create each new rigid body

#    #'2':
#    #    pose: rigid_body_2/pose
#    #    pose2d: rigid_body_2/ground_pose
#    #    frame_id: rigid_body_2/base_link

# optitrack_config:
# #	multicast_address: 192.169.209.203
#        multicast_address: 224.0.0.1
#


# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '0':
        address: 3222
        xPos: 0.000
        yPos: 0.000
    '1':
        address: 3808
        xPos: 0.00
        yPos: 0.00   
    '2':
        address: 3801
        xPos: -0.05
        yPos: -0.05                                                                                                    
   #Use this format to create each new rigid body

   #'2':
   #    pose: rigid_body_2/pose
   #    pose2d: rigid_body_2/ground_pose
   #    frame_id: rigid_body_2/base_link

optitrack_config:
#	multicast_address: 192.169.209.203
       multicast_address: 224.0.0.1
