# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#

# initialize robot using the position from Motive(Optitrack)
# (x, y) = (x0, z0)

rigid_bodies:
    # '0':
    #     address: 3808
    #     xPos: 1.03
    #     yPos: 1.19
    # '1':
    #     address: 3801
    #     xPos: 0.39
    #     yPos: 1.64  
    # '2':
    #     address: 3222
    #     xPos: 0.42
    #     yPos: 1.00 
    '0':
        address: 3749
        xPos: 0.226
        yPos: 0.958
    '1':
        address: 3801
        xPos: 0.629
        yPos: 1.593 
    '2':
        address: 3755
        xPos: 0.032
        yPos: 1.585 
    '3':
        address: 3333
        xPos: 0.032
        yPos: 1.585  
    # '4':
    #     address: 3749
    #     xPos: 0.032
    #     yPos: 1.585                                                                                                      
   #Use this format to create each new rigid body

   #'2':
   #    pose: rigid_body_2/pose
   #    pose2d: rigid_body_2/ground_pose
   #    frame_id: rigid_body_2/base_link

optitrack_config:
#	multicast_address: 192.169.209.203
       multicast_address: 224.0.0.1
