#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '0':
        address: 3776
    '1':
        address: 3790
    '2':
        address: 3758
    '3':
        address: 3756
    '4':
        address: 3791
    '5':
        address: 3735
    '6':
        address: 3807
    '7':
        address: 3748
    '8':
        address: 3761
    '9':
        address: 3765
    '10':
        address: 3724
    '11':
        address: 3806
    '12':
        address: 3788
    '13':
        address: 3773
    '14':
        address: 3777
    '15':
        address: 3780
    '16':
        address: 3774
    '17':
        address: 3787
    '18':
        address: 3752
    '19':
        address: 3733
    '20':
        address: 3732
    '21':
        address: 3803
    '22':
        address: 3808
    '23':
        address: 3781
    '24':
        address: 3821
    '25':
        address: 3764
    '26':
        address: 3738
    '27':
        address: 3822
    '28':
        address: 3714
    '29':
        address: 3658
    '30':
        address: 3740
    '31':
        address: 3778
    '32':
        address: 3769
    '33':
        address: 3222
    '34':
        address: 3789
    '35':
        address: 3782                                                                                                             
   #Use this format to create each new rigid body

   #'2':
   #    pose: rigid_body_2/pose
   #    pose2d: rigid_body_2/ground_pose
   #    frame_id: rigid_body_2/base_link

optitrack_config:
#	multicast_address: 192.169.209.203
       multicast_address: 224.0.0.1
